(() => {
'use strict';
const C=window.WordHiveCore, KEY='bjhWordHive_v1', SCORE_KEY='bjhScoreboard_v1';
const $=id=>document.getElementById(id), copy=x=>JSON.parse(JSON.stringify(x));
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const say=text=>{$('notice').textContent=text;};
let data={version:1,revision:0,selected:null,challenges:[]},blocked=false,activePeriod='',draft=null,index=[],dictionary=new Set(),seeds=[],dictionaryReady=false,postSeason='',outer=[];
function validData(d){return d&&d.version===1&&Number.isInteger(d.revision)&&Array.isArray(d.challenges)&&d.challenges.every(C.validate)&&new Set(d.challenges.map(c=>c.id)).size===d.challenges.length&&(!d.selected||d.challenges.some(c=>c.id===d.selected))&&d.challenges.flatMap(c=>Object.values(c.rounds)).filter(r=>['running','paused'].includes(r.status)).length<=1;}
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!validData(parsed))throw Error('Invalid saved data');data=parsed;}}catch(e){blocked=true;say('Saved Word Hive data could not be read. It has been preserved. Import a valid backup in Teacher controls to recover it.');}
function current(){return data.challenges.find(c=>c.id===data.selected);}
function currentRound(){return current()?.rounds[activePeriod];}
function fresh(){if(blocked)throw Error('Reload this page or import a valid backup before continuing.');const raw=localStorage.getItem(KEY);if(raw&&JSON.parse(raw).revision!==data.revision){blocked=true;throw Error('Word Hive changed in another tab. Reload to use the latest results.');}}
function mutate(fn){fresh();const next=copy(data);fn(next);next.revision=data.revision+1;localStorage.setItem(KEY,JSON.stringify(next));data=next;}
function change(fn){const id=data.selected;mutate(d=>fn(d.challenges.find(c=>c.id===id)));}
function safe(fn){return async(...args)=>{try{await fn(...args);}catch(e){const msg=e.message||'The action could not be completed.';say(msg);if(document.querySelector('dialog[open]'))alert(msg);}};}
function on(id,fn){$(id).onclick=safe(fn);}
function options(el,items,value){el.replaceChildren(...items.map(([v,t])=>{const o=node('option',t);o.value=v;return o;}));if(value)el.value=value;if(el.selectedIndex<0)el.selectedIndex=0;}
function running(){return data.challenges.flatMap(c=>c.periods.map(p=>({c,p,r:c.rounds[p.id]}))).find(x=>['running','paused'].includes(x.r.status));}
function expireAll(){if(blocked)return;const now=Date.now();if(data.challenges.some(c=>Object.values(c.rounds).some(r=>r.status==='running'&&C.remaining(r,now)===0))){mutate(d=>d.challenges.forEach(c=>Object.values(c.rounds).forEach(r=>C.expire(r,now))));render();}}
function time(ms){const seconds=Math.ceil(ms/1000);return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}
function feedback(text){$('feedback').textContent=text;}
function paintHive(){const c=current();if(!c)return;const rest=c.letters.split('').filter(x=>x!==c.center);if(outer.slice().sort().join('')!==rest.join(''))outer=rest;const enabled=currentRound()?.status==='running'&&!c.posted&&!blocked;$('hive').replaceChildren(...[c.center,...outer].map((letter,i)=>{const b=node('button',letter.toUpperCase(),'hex'+(i===0?' center':''));b.type='button';b.disabled=!enabled;b.setAttribute('aria-label',letter.toUpperCase()+(i===0?', required center letter':''));b.onclick=()=>{if(C.remaining(currentRound())<=0){safe(expireAll)();return;}$('guess').value+=letter;$('guess').focus();};return b;}));}
function render(){const c=current();$('empty').hidden=!!c;$('game').hidden=!c;if(!c){renderTeacher();return;}if(!c.periods.some(p=>p.id===activePeriod))activePeriod=c.periods.find(p=>['running','paused'].includes(c.rounds[p.id].status))?.id||c.periods.find(p=>p.id===String(DashboardData.getCurrentClassId()))?.id||c.periods[0].id;
options($('period'),c.periods.map(p=>[p.id,p.name]),activePeriod);$('challengeTitle').textContent=c.title;$('challengeDate').textContent=new Date(c.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})+' · '+c.durationMs/60000+' MINUTES PER CLASS';
const r=currentRound();$('roundStatus').textContent=c.posted?'RESULTS POSTED':r.status.toUpperCase();$('score').textContent=C.roundScore(c,r);const accepted=r.attempts.filter(w=>c.words.includes(w)).sort();$('foundCount').textContent=accepted.length;$('found').replaceChildren(...accepted.map(w=>node('span',w,C.letters(w).length===7?'word pangram':'word')));if(!accepted.length)$('found').append(node('p',r.status==='ready'?'A fresh word list for this class.':'Your accepted words will appear here.','subtle'));
const enabled=r.status==='running'&&!c.posted&&!blocked;for(const id of ['guess','enter','delete'])$(id).disabled=!enabled;$('startRound').hidden=r.status!=='ready'||!!c.posted;$('startRound').disabled=!!running()||blocked;$('startRound').textContent='Start '+c.durationMs/60000+'-minute round';
$('roundNote').textContent=r.status==='ready'?(running()?'Finish the active round before starting this class.':'The timer starts when you click Start.'):r.status==='running'?'The timer continues if you refresh or leave this page.':r.status==='paused'?'Round paused. Resume in Teacher controls.':r.status==='excluded'?'This class is excluded from this challenge.':'Round complete. Results are saved for the teacher.';
paintHive();paintClock();renderTeacher();}
function paintClock(){const r=currentRound();if(!r)return;const ms=C.remaining(r);$('timer').textContent=time(ms);$('timer').classList.toggle('urgent',r.status==='running'&&ms<=30000);}
function renderTeacher(){options($('challengeSelect'),data.challenges.map(c=>[c.id,c.title+(c.posted?' · Posted':'')]),data.selected);$('teacherCurrent').hidden=!current();const c=current();if(!c)return;const r=currentRound();$('pause').disabled=!r||!['running','paused'].includes(r.status)||!!c.posted;$('pause').textContent=r?.status==='paused'?'Resume current round':'Pause current round';$('finish').disabled=!r||!['running','paused'].includes(r.status)||!!c.posted;
$('resultNote').textContent='Complete each period or exclude periods that will not play. Earlier classes’ answers are hidden on the game screen.';$('results').replaceChildren(...c.periods.map(p=>{const round=c.rounds[p.id],tr=node('tr');const found=round.attempts.filter(w=>c.words.includes(w));for(const text of [p.name,round.status,found.length,C.roundScore(c,round)])tr.append(node('td',String(text)));const cell=node('td');if(['ready','excluded'].includes(round.status)&&!c.posted){const b=node('button',round.status==='excluded'?'Include':'Exclude');b.onclick=safe(()=>{change(ch=>{ch.rounds[p.id].status=round.status==='excluded'?'ready':'excluded';});render();});cell.append(b);}else cell.textContent=round.status==='excluded'?'Excluded':'Included';tr.append(cell);return tr;}));
$('disputes').disabled=!C.ready(c)||!!c.posted;$('post').disabled=!C.ready(c)||!!c.posted;$('postedMessage').textContent=c.posted?'Posted to '+c.posted.season+'.':'Results have not been posted to the scoreboard.';}
$('period').onchange=safe(()=>{activePeriod=$('period').value;$('guess').value='';feedback('Use the gold center letter in every word.');render();});
on('startRound',()=>{expireAll();if(running())throw Error('Finish the active round first.');if(current().posted||currentRound().status!=='ready')return;change(c=>{const r=c.rounds[activePeriod];r.status='running';r.remainingMs=c.durationMs;r.startedAt=Date.now();r.deadline=r.startedAt+c.durationMs;});render();$('guess').focus();});
$('guessForm').onsubmit=safe(e=>{e.preventDefault();expireAll();const c=current(),r=currentRound();if(!c||r.status!=='running'||c.posted||C.remaining(r)===0)return;const word=C.normalize($('guess').value);if(!/^[a-z]+$/.test(word)){feedback('Use letters A–Z only.');return;}if(word.length<4){feedback('Use at least four letters.');return;}if(!word.includes(c.center)){feedback('Include the gold center letter.');return;}if([...word].some(l=>!c.letters.includes(l))){feedback('Use only the seven hive letters.');return;}if(r.attempts.includes(word)){feedback('You already tried that word.');return;}change(ch=>ch.rounds[activePeriod].attempts.push(word));const accepted=c.words.includes(word);feedback(accepted?(C.letters(word).length===7?'Pangram! ':'')+'+'+C.points(word)+' points':'Not in this word bank. Saved for teacher review.');$('guess').value='';render();$('guess').focus();});
on('delete',()=>{$('guess').value=$('guess').value.slice(0,-1);$('guess').focus();});on('shuffle',()=>{for(let i=outer.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[outer[i],outer[j]]=[outer[j],outer[i]];}paintHive();});
on('teacher',()=>{expireAll();renderTeacher();$('teacherDialog').showModal();});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('challengeSelect').onchange=safe(()=>{mutate(d=>d.selected=$('challengeSelect').value);activePeriod='';$('guess').value='';feedback('Use the gold center letter in every word.');render();});
on('pause',()=>{expireAll();const r=currentRound();if(r.status==='running'){change(c=>{const round=c.rounds[activePeriod];round.remainingMs=C.remaining(round);round.status='paused';round.deadline=null;});}else if(r.status==='paused'){change(c=>{const round=c.rounds[activePeriod];round.deadline=Date.now()+round.remainingMs;round.status='running';});}render();});
on('finish',()=>{expireAll();if(!['running','paused'].includes(currentRound().status))return;if(!confirm('End this class’s round early? No more words can be entered for this period.'))return;change(c=>{const r=c.rounds[activePeriod];r.remainingMs=C.remaining(r);r.status='finished';r.finishedAt=Date.now();r.deadline=null;});render();});
function newChallenge(){if(running())throw Error('Finish the active round before creating another challenge.');$('teacherDialog').close();draft=null;$('preview').hidden=true;$('title').value='Word Hive · '+new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'});$('reviewed').checked=false;$('setupDialog').showModal();}
on('newChallenge',newChallenge);on('createFirst',newChallenge);
function resetPreview(){draft=null;$('preview').hidden=true;$('reviewed').checked=false;}
function setCenters(){resetPreview();const hive=$('method').value==='letters'?$('letters').value.replace(/\s/g,''):$('method').value==='pangram'?$('pangram').value.trim():'';options($('center'),[['auto','Choose automatically'],...C.letters(hive).split('').filter(l=>/[a-z]/.test(l)).map(l=>[l,l.toUpperCase()])]);}
$('method').onchange=()=>{$('letterLabel').hidden=$('method').value!=='letters';$('pangramLabel').hidden=$('method').value!=='pangram';setCenters();};$('letters').oninput=setCenters;$('pangram').oninput=setCenters;$('center').onchange=resetPreview;$('bank').oninput=()=>{$('reviewed').checked=false;};
function build(hive,center){if(center!=='auto')return C.puzzle(index,hive,center);const possibilities=[];for(const letter of hive){try{possibilities.push(C.puzzle(index,hive,letter));}catch{}}if(!possibilities.length)throw Error('No playable center letter found. Try another hive.');return possibilities.sort((a,b)=>Math.abs(a.words.length-60)-Math.abs(b.words.length-60))[0];}
on('generate',async()=>{if(!dictionaryReady)throw Error('The dictionary is still loading. If it failed, refresh the page.');$('generate').disabled=true;resetPreview();try{await new Promise(resolve=>setTimeout(resolve,0));const method=$('method').value;let hive;if(method==='random'){const shuffled=seeds.slice();for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}for(const seed of shuffled){try{const candidate=build(C.letters(seed),'auto');if(candidate.words.length<=180){draft=candidate;break;}}catch{}}if(!draft)throw Error('No random puzzle is available. Try entering your own pangram.');}else{const raw=C.normalize(method==='letters'?$('letters').value.replace(/\s/g,''):$('pangram').value);if(!/^[a-z]+$/.test(raw))throw Error('Enter letters A–Z only.');if(method==='letters'&&raw.length!==7)throw Error('Enter seven different letters, without repeats.');hive=C.letters(raw);if(hive.length!==7)throw Error('The puzzle needs exactly seven unique letters.');if(method==='pangram'&&!dictionary.has(raw))throw Error('That pangram is not in the built-in dictionary. Use Choose seven letters, then add your word to the answer bank.');draft=build(hive,$('center').value);} $('previewLetters').textContent=draft.letters.toUpperCase().split('').join(' · ')+' — CENTER: '+draft.center.toUpperCase();$('bankCount').textContent=draft.words.length+' words · '+draft.words.reduce((s,w)=>s+C.points(w),0)+' possible points · Pangrams: '+draft.words.filter(w=>C.letters(w).length===7).join(', ');$('bank').value=draft.words.join('\n');$('preview').hidden=false;}finally{$('generate').disabled=false;}});
on('saveChallenge',()=>{if(!draft)throw Error('Generate a puzzle first.');if(running())throw Error('Finish the active round first.');const title=$('title').value.trim(),minutes=Number($('minutes').value);if(!title)throw Error('Enter a challenge name.');if(!Number.isInteger(minutes)||minutes<1||minutes>60)throw Error('Choose a whole number from 1 to 60 minutes.');const words=[...new Set($('bank').value.split(/[\s,]+/).map(C.normalize).filter(Boolean))].sort();if(words.length<10)throw Error('Keep at least 10 words in the answer bank.');if(words.some(w=>!C.validWord(w,draft.letters,draft.center)))throw Error('Every answer must have at least four letters, use only the hive letters, and include the center.');if(!words.some(w=>C.letters(w).length===7))throw Error('Keep at least one pangram.');if(!$('reviewed').checked)throw Error('Review the answer bank and check the confirmation box.');const periods=DashboardData.getClasses({activeOnly:true}).map(p=>({id:String(p.id),name:p.name}));if(!periods.length)throw Error('Enable at least one class in Dashboard Settings.');const c={id:uid(),title,letters:draft.letters,center:draft.center,words,durationMs:minutes*60000,createdAt:Date.now(),periods,rounds:Object.fromEntries(periods.map(p=>[p.id,{status:'ready',remainingMs:minutes*60000,deadline:null,attempts:[]}])),posted:null};mutate(d=>{d.challenges.push(c);d.selected=c.id;});activePeriod='';$('setupDialog').close();render();say('Challenge saved. Every included class gets the same puzzle and time limit.');});
function disputes(){const c=current(),bank=new Set(c.words);return [...new Set(c.periods.flatMap(p=>c.rounds[p.id].attempts.filter(w=>!bank.has(w))))].sort();}
function renderDisputes(){const words=disputes();$('disputeList').replaceChildren(...words.map(word=>{const row=node('div',undefined,'dispute-row');row.append(node('strong',word));const b=node('button','Approve for every class');b.onclick=safe(()=>{const c=current();if(!C.ready(c)||c.posted)throw Error('Corrections are only available after all rounds end and before posting.');if(!confirm('Accept “'+word+'” and credit every class that tried it?'))return;change(ch=>{if(!ch.words.includes(word))ch.words.push(word);});render();renderDisputes();});row.append(b);return row;}));if(!words.length)$('disputeList').append(node('p','No disputed words to review.'));}
on('disputes',()=>{if(!C.ready(current())||current().posted)return;renderDisputes();$('disputeDialog').showModal();});
function scoreboard(){const raw=localStorage.getItem(SCORE_KEY);let s=raw?JSON.parse(raw):{schemaVersion:4,activeSeason:'Fall Semester Championship',seasons:{}};if(Array.isArray(s.events)){const title=s.seasonName||'Fall Semester Championship';s={schemaVersion:4,activeSeason:title,seasons:{[title]:{events:s.events}}};}if(!s||typeof s.activeSeason!=='string'||!s.seasons||typeof s.seasons!=='object'||Object.values(s.seasons).some(x=>!Array.isArray(x.events)))throw Error('Scoreboard data could not be read. Open Scoreboard to check it before posting.');return s;}
on('post',()=>{expireAll();const c=current();if(!C.ready(c)||c.posted)throw Error('Finish or exclude every class before posting.');postSeason=scoreboard().activeSeason;$('postTarget').textContent=c.title+' → '+postSeason;$('awardRows').replaceChildren(...C.awards(c).map(row=>{const tr=node('tr');[row.name,row.score,row.award].forEach(x=>tr.append(node('td',String(x))));return tr;}));$('postDialog').showModal();});
on('confirmPost',async()=>{const id=data.selected;$('confirmPost').disabled=true;try{const write=()=>{fresh();const c=current();if(c.id!==id||!C.ready(c))throw Error('The challenge changed. Open a new preview.');const s=scoreboard(),eventId='word-hive-'+c.id;const prior=Object.entries(s.seasons).find(([name,season])=>season.events.some(e=>e.id===eventId));if(prior){change(ch=>ch.posted={season:prior[0],at:Date.now(),eventId});}else{if(c.posted)throw Error('This challenge was already posted.');if(s.activeSeason!==postSeason)throw Error('The active championship changed. Cancel and reopen the preview.');const rows=C.awards(c);s.seasons[postSeason]??={events:[]};s.seasons[postSeason].events.push({id:eventId,type:'competition',date:new Date().toISOString(),reason:'Word Hive: '+c.title,scoringMethod:'balanced',scoringScale:10,gameScores:Object.fromEntries(rows.map(p=>[p.id,p.score])),changes:Object.fromEntries(rows.map(p=>[p.id,p.award]))});localStorage.setItem(SCORE_KEY,JSON.stringify(s));change(ch=>ch.posted={season:postSeason,at:Date.now(),eventId});}$('postDialog').close();render();say(prior?'These results were already posted; no duplicate points were added.':'Class results posted to the scoreboard.');};if(navigator.locks)await navigator.locks.request('bjh-scoreboard-write',write);else write();}finally{$('confirmPost').disabled=false;}});
on('export',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='Word-Hive-Backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
on('import',()=>$('importFile').click());$('importFile').onchange=safe(async()=>{const f=$('importFile').files[0];if(!f)return;try{if(f.size>10000000)throw Error('Choose a Word Hive backup smaller than 10 MB.');const next=JSON.parse(await f.text());if(!validData(next))throw Error('This is not a valid Word Hive backup.');if(!confirm('Replace Word Hive challenges and results in this browser with this backup? Scoreboard entries will not be changed.'))return;next.revision=data.revision+1;localStorage.setItem(KEY,JSON.stringify(next));data=next;blocked=false;activePeriod='';expireAll();render();say('Word Hive backup imported.');}finally{$('importFile').value='';}});
on('fullscreen',async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen();});document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';});
window.addEventListener('storage',e=>{if(e.key===KEY||e.key===null){blocked=true;say('Word Hive changed in another tab. Reload this page to continue with the latest scores.');document.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);}});
document.addEventListener('visibilitychange',()=>{safe(expireAll)();paintClock();});setInterval(()=>{safe(expireAll)();paintClock();},250);
(async()=>{try{const response=await fetch('shared/word-hive-dictionary.json');if(!response.ok)throw Error('Dictionary file could not be loaded.');const d=await response.json();if(!Array.isArray(d.words)||!Array.isArray(d.seeds))throw Error('Invalid dictionary file.');dictionary=new Set(d.words);index=d.words.map(word=>({word,mask:C.mask(word)}));seeds=d.seeds;dictionaryReady=true;$('dictionaryStatus').textContent=dictionary.size.toLocaleString()+' words available';$('generate').disabled=false;}catch(e){$('dictionaryStatus').textContent='Dictionary unavailable. Upload shared/word-hive-dictionary.json and refresh.';$('generate').disabled=true;say('The dictionary could not load. Saved challenges can still be played.');}})();
$('generate').disabled=true;try{expireAll();render();}catch(e){blocked=true;say(e.message);}
})();
